### ISSUE TITLE
Git clone 后，编译运行报错。

### ISSUE THREAD

**Issue by unitepower** [A-Donga/PluginTest#1]
指针错误？

插件目录生成 .so 文件
`go build --buildmode=plugin -o HelloPlugin.so HelloPlugin.go`
`go build --buildmode=plugin -o TestPlugin.so TestPlugin.go`
编译主程序并运行
`go run cmd/MainFile.go`

An error occurred while search target info : [plugins/HelloPlugin.so]
plugin: symbol PluginBaseInfo not found in plugin plugin/unnamed-2db8398469366e079bcddaea989370135b30e628
Can find base info.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40d0473]

goroutine 1 [running]:
PluginTest.LoadAllPlugin(0xc000102000, 0x5, 0x8, 0x5, 0x8, 0x14)
	/Users/ss/Documents/dev/goplugin/PluginTest/pluginSupport.go:52 +0x233
main.init.0()
	/Users/ss/Documents/dev/goplugin/PluginTest/cmd/MainFile.go:61 +0xb4
exit status 2

**Comment by unitepower** [comment]
把 HelloPlugin.go 以下代码打开即可。
var PluginBaseInfo = PluginTest.PluginBaseInfo{
	Name:        "hello plugin",
	ActiveFlag:  PluginTest.PrintItemActive,
	ActivePoint: true,           //目标任务执行前运行
	Functions:   "PrintNowTime", //可用函数名
}
